name: Keep Streamlit App Awake

on:
  schedule:
    # Runs everyday at 8:00 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        # Pings the app to prevent it from going to sleep
        run: curl -sL https://app.fulfillsense.com/risk-dashboard > /dev/null
